apiVersion: apps/v1
kind: Deployment 
metadata:
  name: chatapp-deployment
  labels:
    app: chatapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatapp 
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: gopal1409/chatbotapp
        ports:
        - containerPort: 8080
